### ISSUE TITLE
Adding a stream can be done without creating a file

### ISSUE THREAD

**Issue by Arash-Afshar** [RobinDavid/pyADS#3]
The problem with writing the property to a file is that it becomes a shared resource in multi-threaded environments where you want to add the same property "name" with different contents for each file. Therefore, it would require synchronizations, etc. But directly writing the content of the property does not have this restriction.
Following is one way of implementing it without requiring to write the property content to a file:

```
def addStream(self, stream, content):
    if os.path.exists("%s:%s" % (self.filename, stream)):
        print "A Stream with the same name already exist."
        return False

    fd = open("%s:%s" % (self.filename, stream), "wb")
    fd.write(content)
    fd.close()
    self.streams.append(stream)
    return True
```

**Comment by Alexey-T** [comment]
Done it in fork https://github.com/Alexey-T/pyADS

**Comment by RobinDavid** [comment]
Hey @Arash-Afshar  and @Alexey-T I managed to find the time to integrate both of your modifications in pyADS. Feel free to take a look.
