### ISSUE TITLE
Closing the stream

### ISSUE THREAD

**Issue by Arash-Afshar** [RobinDavid/pyADS#4]
A call to kernel32.FindFirstStreamW should eventually be followed by a call to kernel32.FindClose
I suggest adding a close function that calls kernel32.FindClose.

**Comment by Neo23x0** [comment]
This issue is open for so long. I guess we have to close this and provide a pull request or a fork of this library.

**Comment by RobinDavid** [comment]
Hi @Neo23x0! I have very few time to work and keep maintaining this project. I am really open on pull request, do not hesitate making a pull request, I would be happy to merge it :wink:

**Comment by RobinDavid** [comment]
@Arash-Afshar  I have added it. (I am going to reject the pull request but it comes back to the same)
