### ISSUE TITLE
WIN32_FIND_STREAM_DATA buffer size seems incorrect

### ISSUE THREAD

**Issue by b0bh00d** [RobinDavid/pyADS#6]
The WIN32_FIND_STREAM_DATA definition states that cStreamName is "MAX_PATH + 36".  Your code defines this as 164, but in fact, MAX_PATH is 260.  This means that cStreamName should actually be 260 + 36 = 296, not 164.

I tried using your code in Python, and it crashed for me.  When I corrected the buffer width from 164 to 296, the crashing stopped.

**Comment by RobinDavid** [comment]
Corrected in b4d28e435df66759f957b058b820b4a548fabdef
